var GameResources = [

    /* Radmars Logo */
    { name: "intro_bg",       type: "image", src: "data/intro_bg.png"       },
    { name: "intro_glasses1", type: "image", src: "data/intro_glasses1.png" },
    { name: "intro_glasses2", type: "image", src: "data/intro_glasses2.png" },
    { name: "intro_glasses3", type: "image", src: "data/intro_glasses3.png" },
    { name: "intro_glasses4", type: "image", src: "data/intro_glasses4.png" },
    { name: "intro_mars",     type: "image", src: "data/intro_mars.png"     },
    { name: "intro_radmars1", type: "image", src: "data/intro_radmars1.png" },
    { name: "intro_radmars2", type: "image", src: "data/intro_radmars2.png" },
    { name: "radmarslogo",     type: "audio", src: "data/", channels: 2     },

    { name: "boss1_1", type: "image", src: "data/boss1_1.png" },
    { name: "boss1_2", type: "image", src: "data/boss1_2.png" },
    { name: "boss1_3", type: "image", src: "data/boss1_3.png" },

    { name: "boss2_1", type: "image", src: "data/boss2_1.png" },
    { name: "boss2_2", type: "image", src: "data/boss2_2.png" },
    { name: "boss2_3", type: "image", src: "data/boss2_3.png" },
    { name: "boss3_1", type: "image", src: "data/boss3_1.png" },

    { name: "player", type: "image", src: "data/player.png" },
    { name: "player_halo", type: "image", src: "data/player_halo.png" },

    { name: "player_hp_back", type: "image", src: "data/player_hp_back.png" },
    { name: "player_hp_bar", type: "image", src: "data/player_hp_bar.png" },
    { name: "player_hp_front", type: "image", src: "data/player_hp_front.png" },

    { name: "boss_hp_back", type: "image", src: "data/boss_hp_back.png" },
    { name: "boss_hp_bar", type: "image", src: "data/boss_hp_bar.png" },
    { name: "boss_hp_front", type: "image", src: "data/boss_hp_front.png" },

    { name: "shockwave", type: "image", src: "data/shockwave.png" },
    { name: "beam", type: "image", src: "data/beam.png" },
    { name: "explode", type: "image", src: "data/explode.png" },
    { name: "wordchunk1", type: "image", src: "data/wordchunk1.png" },
    { name: "wordchunk2", type: "image", src: "data/wordchunk2.png" },
    { name: "wordchunk3", type: "image", src: "data/wordchunk3.png" },
    { name: "wordchunk4", type: "image", src: "data/wordchunk4.png" },
    { name: "wordchunk5", type: "image", src: "data/wordchunk5.png" },

    { name: "answer_box", type: "image", src: "data/answer_box.png" },

    { name: "talkscene_bg", type: "image", src: "data/talkscene_bg.png" },
    { name: "title_bg", type: "image", src: "data/title_bg.png" },
    { name: "title_title", type: "image", src: "data/title_title.png" },
    { name: "bg_sky", type: "image", src: "data/bg_sky.png" },
    { name: "bg_wall", type: "image", src: "data/bg_wall.png" },
    { name: "introcta", type: "image", src: "data/introcta.png" },
    { name: "gameover", type: "image", src: "data/gameover.png" },

    { name: "16x16_font", type: "image", src: "data/16x16_font.png" },
    { name: "16x16_font_blue", type: "image", src: "data/16x16_font_blue.png" },
    { name: "32x32_font", type: "image", src: "data/32x32_font.png" },
    { name: "64x64_font", type: "image", src: "data/64x64_font.png" },

    { name: "beam",     type: "audio", src: "data/", channels: 2     },
    { name: "beamcharge",     type: "audio", src: "data/", channels: 2     },
    { name: "explosion",     type: "audio", src: "data/", channels: 2     },
    { name: "hit",     type: "audio", src: "data/", channels: 2     },
    { name: "miss",     type: "audio", src: "data/", channels: 2     },
    { name: "type1",     type: "audio", src: "data/", channels: 2     },
    { name: "type2",     type: "audio", src: "data/", channels: 2     },
    { name: "type3",     type: "audio", src: "data/", channels: 2     },
    { name: "type4",     type: "audio", src: "data/", channels: 2     },
    { name: "type5",     type: "audio", src: "data/", channels: 2     },
    { name: "type6",     type: "audio", src: "data/", channels: 2     },
    { name: "type7",     type: "audio", src: "data/", channels: 2     },
    { name: "speech1-1",     type: "audio", src: "data/", channels: 2     },
    { name: "speech1-2",     type: "audio", src: "data/", channels: 2     },
    { name: "speech1-3",     type: "audio", src: "data/", channels: 2     },
    { name: "speech1-4",     type: "audio", src: "data/", channels: 2     },
    { name: "speech1-5",     type: "audio", src: "data/", channels: 2     },
    { name: "speech1-6",     type: "audio", src: "data/", channels: 2     },
    { name: "speech1-7",     type: "audio", src: "data/", channels: 2     },
    { name: "speech2-1",     type: "audio", src: "data/", channels: 2     },
    { name: "speech2-2",     type: "audio", src: "data/", channels: 2     },
    { name: "speech2-3",     type: "audio", src: "data/", channels: 2     },
    { name: "speech2-4",     type: "audio", src: "data/", channels: 2     },
    { name: "speech2-5",     type: "audio", src: "data/", channels: 2     },
    { name: "speech2-6",     type: "audio", src: "data/", channels: 2     },
    { name: "speech2-7",     type: "audio", src: "data/", channels: 2     },
    { name: "speech3-1",     type: "audio", src: "data/", channels: 2     },
    { name: "speech3-2",     type: "audio", src: "data/", channels: 2     },
    { name: "speech3-3",     type: "audio", src: "data/", channels: 2     },
    { name: "speech3-4",     type: "audio", src: "data/", channels: 2     },
    { name: "speech3-5",     type: "audio", src: "data/", channels: 2     },
    { name: "speech3-6",     type: "audio", src: "data/", channels: 2     },
    { name: "speech3-7",     type: "audio", src: "data/", channels: 2     },

];
